name: mtc_analytics
description: All in one. This package was created to simplify the job of logging events across different analytics platforms.
version: 3.0.0
homepage: https://github.com/crab-team/mtc-analytics

environment:
  sdk: ">=2.18.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  amplitude_flutter: ^4.6.2
  firebase_analytics: ^12.4.5
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter: null
