name: mtc_analytics
description: All in one. This package was created to simplify the job of logging events across different analytics platforms.
version: 1.2.0+11
homepage: https://github.com/crab-team/mtc-analytics

environment:
  sdk: ">=2.18.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  amplitude_flutter: ^3.13.0
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
